### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by camoody1** [MackinationsAi/Upgraded-Depth-Anything-V2#1]
Hello. Allow me to begin with... I am an idiot.

I accidentally installed this on a drive that I didn't want it on. And, as I stated earlier, I am an idiot. How can I go about uninstalling this from the drive? Is it as simple as deleting the "Upgraded-Depth-Anything-V2" folder that was copied down from GitHub? Please say it's as simple as deleting that folder because as I stated earlier... I am an idiot.

Thank you for your help.

**Comment by MackinationsAi** [comment]
It's as simple as deleting the "Upgraded-Depth-Anything-V2" folder.

**Comment by camoody1** [comment]
> It's as simple as deleting the "Upgraded-Depth-Anything-V2" folder.

Thank you, my child.🙏🏼
