### ISSUE TITLE
Still receiving ERROR: triton-2.1.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by ricku425** [MackinationsAi/Upgraded-Depth-Anything-V2#11]
Sorry to open a new ticket on this, I'm not very familiar with GitHub and wasn't sure if I should have replied to the old thread. Anyway...

I am receiving the "ERROR: triton-2.1.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform."

I have tried all the fixes from your previous post a few months ago, but nothing seems to have any effect. I am running Windows 11, Python 3.13.1, and Cuda 12.6.3.

I have tried manually downloading the Triton wheel from your GitHub, but that doesn't seem to make any difference, either.

Not sure if it matters, but I also receive the two following errors (but they don't cause the one_click_install to bomb):
ERROR: Could not find a version that satisfies the requirement torch==2.3.0+cu121 (from versions: none)
ERROR: No matching distribution found for torch==2.3.0+cu121

**Comment by MackinationsAi** [comment]
You're running python==3.13.1 & there currently isn't a triton wheel that works w/ that version of python - https://huggingface.co/MackinationsAi/site-packages/tree/main/triton. If you are able to get the gradio up & running, triton is not strictly necessary for this repo to work though, it helps optimize xformers but you should be fine w/o it. If you do run into any issues getting everything going then let me know here, I am going to close this issue ticket on Monday if I don't here back from you by then.

**Comment by ricku425** [comment]
I downgraded my Python to 3.10.11 and BOOM! Everything works like a charm. Cannot thank you enough! Consider this closed.
