### ISSUE TITLE
CPU error "NotImplementedError: No operator found for `memory_efficient_attention_forward`"

### ISSUE THREAD

**Issue by ThatDocBoi** [MackinationsAi/Upgraded-Depth-Anything-V2#6]
Hey, is there any way to make this run on a cpu? I know the original repo worked with it and it'd be great if this could as well. I installed per the instructions and am getting this error:
```
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2443, 16, 64) (torch.float32)
     key         : shape=(1, 2443, 16, 64) (torch.float32)
     value       : shape=(1, 2443, 16, 64) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`decoderF` is not supported because:
    device=cpu (supported: {'cuda'})
    attn_bias type is <class 'NoneType'>
`flshattF@v2.5.6` is not supported because:
    device=cpu (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    device=cpu (supported: {'cuda'})
    unsupported embed per head: 64
```

Thanks!

**Comment by MackinationsAi** [comment]
I was actually thinking about adding the option for the user you choose between cpu & gpu torch or mps. It would have more limited capabilities running on a cpu though. It's on my list.

**Comment by heyoeyo** [comment]
In case this is still an issue, the error comes from using xformers (which doesn't work on cpu) you can fix it by uninstalling the library: `pip uninstall xformers`

If you can't uninstall it for some reason (e.g. it breaks something else you have installed), then it should be possible to manually disable xformers usage by setting `XFORMERS_AVAILABLE = False` in the [block](https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2/blob/1b61d88c52fe6c179785c64d0798458db18d925c/depth_anything_v2/dinov2_layers/block.py#L30) and [attention](https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2/blob/1b61d88c52fe6c179785c64d0798458db18d925c/depth_anything_v2/dinov2_layers/attention.py#L23) scripts.
