### ISSUE TITLE
The Windows installation uses GLOB and a forward slash in the  OS file selection code. 

### ISSUE THREAD

**Issue by micropsyche** [MackinationsAi/Upgraded-Depth-Anything-V2#9]
Have installed locally under windows and can get no results. Closer examination shows that in run_image-depth_8bit.py, lines 33 to 37 appear to be causing a problem. As I understand it GLOB is a Unix style pathname expander and the path separator  for windows is a backslash and a not a forward slash as coded. Running  the  code just won't work and I am not a coder and can't get around it.

**Comment by MackinationsAi** [comment]
Fixed w/ [update](https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2/commit/447e8f13e8b511bf8874a301a7c0e0ed25ad9edc). Apologies for the delayed response, haven't had much free-time until now! I have updated all of the CLI scripts to handle the pathname more adaptively for both windows, macOS & linux users, as well as adding an additional function to remove double quotes from the path if present. @micropsyche thank you for bringing this to my attention!
